version: "3.9"

services:
  # Main app
  flask_api:
    build: .
    container_name: flask_api
    ports:
      - "5000:5000"
    depends_on:
      - flask_redis
      - flask_mongo

  #  # Caching and in-memory storage
  #  flask_redis:
  #    container_name: flask_redis
  #    image: redis:6.2.6-bullseye
  #    ports:
  #      - "6379"

  # Database
  flask_mongo:
    container_name: flask_mongo
    image: mongo:5.0
    ports:
      - "27017"
    volumes:
      - "mongodb:/data/db"
      - "mongoconfig:/data/configdb"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}

volumes:
  mongodb:
  mongoconfig:
